new hudson build

diff --git a/mdsplus/devscripts/pkg b/mdsplus/devscripts/pkg
--- a/mdsplus/devscripts/pkg
+++ b/mdsplus/devscripts/pkg
@@ -731,16 +731,6 @@ EOF
      status="ok"
      if [ "$need_to_build" == "yes" ]
      then
-       rpmbuild --target x86_64-linux --buildroot $rpmdir/BUILDROOT/x86_64 -ba --define="_topdir $rpmdir" --define="_builddir $rpmdir/BUILD/x86_64" $specfile 
-       rpmbuild_status=$?
-       if [ "rpmbuild_status" != "0" ]
-       then
-         if [ ! -z "$notify" ]
-         then
-           echo "Error building x86_64 ${flavor}.${REDHATDIST} rpms." >> $notify
-         fi
-         status="error"
-       fi
        rpmbuild --target i686-linux --buildroot $rpmdir/BUILDROOT/i686 -ba --define="_topdir $rpmdir" --define="_builddir $rpmdir/BUILD/i686" $specfile
        rpmbuild_status=$?
        if [ "rpmbuild_status" != "0" ]
@@ -750,6 +740,17 @@ EOF
            echo "Error building i686 ${flavor}.${REDHATDIST} rpms." >> $notify
          fi
          status="error"
+       else
+         rpmbuild --target x86_64-linux --buildroot $rpmdir/BUILDROOT/x86_64 -ba --define="_topdir $rpmdir" --define="_builddir $rpmdir/BUILD/x86_64" $specfile 
+         rpmbuild_status=$?
+         if [ "rpmbuild_status" != "0" ]
+         then
+           if [ ! -z "$notify" ]
+           then
+             echo "Error building x86_64 ${flavor}.${REDHATDIST} rpms." >> $notify
+           fi
+           status="error"
+         fi
        fi
      else
        status="skip"
